app:
  name: "wechat_login"
  mode: "dev"
  port: 8080
  version: "0.0.1"
  start_time: "2023-03-30"
  machine_id: 1

log:
  level: "debug"
  filename: "wechat_login.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "xxx"
  dbname: "wechat_login"
  max_open: 200
  max_idle: 10

redis:
  host: "127.0.0.1"
  password: ""
  pool: 20
  port: 6379
  db: 0

wechat:
  appID: "xxx"
  appSecret: "xxx"
  token: "xxx"